<a href="https://colab.research.google.com/github/SriSatyaLokesh/some-app-for-whatsapp/blob/master/notebooks/analytics/Cleaning_Whatsapp_chat_file.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from google.colab import files
uploaded = files.upload()

Saving WhatsApp Chat with CSE 2K16-2K20.txt to WhatsApp Chat with CSE 2K16-2K20 (4).txt

In [1]:
import pandas as pd
from itertools import chain, repeat
import re

chainer = chain.from_iterable
class Cleaner:
  def __init__(self,filename):
    self.filename = filename

  def _clean_data(self):
    chat_file = self.filename
    with open(chat_file) as file:
      all_msgs = file.readlines()
      raw_texts = []
      for line in all_msgs:
        if re.match("^\d{2}/\d{2}/\d{2},\s\d{1,2}:\d{2}\s[ap]m",line):
          date_split = line.split(' - ') #date and user
          user_split = date_split[1].split(':')
          if len(user_split) >= 2:
            raw_texts.append(line)
        else:
          try:
            raw_texts[-1] += line
          except Exception as err:
            print(line,raw_texts)
            print(err)

    return raw_texts 
      
  def _get_data(self):
    raw_texts = self._clean_data()
    raw_messages = dict()
    for line in raw_texts:
      date_split = line.split(' - ')
      user_split = date_split[1].split(':')
      user = user_split[0]
      if user not in raw_messages:
        raw_messages[user] = [line]
      else:
        raw_messages[user].append(line)

    df = pd.DataFrame({'user': list(chainer(repeat(k, len(v)) for k,v in raw_messages.items())),
                   'raw_message': list(chainer(raw_messages.values()))}) 
    return df

chat_file = input()
clean = Cleaner(chat_file)
raw_msgs_df = clean._get_data()
raw_msgs_df

WhatsApp Chat with CSE 2K16-2K20 (4).txt

                user                                        raw_message
0    +91 73311 74849     17/07/19, 8:21 pm - +91 73311 74849: Yes sir\n
1    +91 73311 74849  02/08/19, 7:23 pm - +91 73311 74849: <Media om...
2    +91 80965 40660  17/07/19, 8:32 pm - +91 80965 40660: Sir tomm ...
3    +91 80965 40660  08/08/19, 6:28 pm - +91 80965 40660: This mess...
4    +91 98667 58870     17/07/19, 8:32 pm - +91 98667 58870: Infy TQ\n
..               ...                                                ...
632  +91 98483 13908  25/04/20, 1:30 pm - +91 98483 13908: This mess...
633  +91 98483 13908  25/04/20, 1:33 pm - +91 98483 13908: Sir, most...
634  +91 79934 07020  25/04/20, 1:40 pm - +91 79934 07020: Sir, plea...
635  +91 73828 52692  25/04/20, 1:41 pm - +91 73828 52692: Sir, plea...
636  +91 90106 66088  25/04/20, 1:43 pm - +91 90106 66088: Yes sir w...

[637 rows x 2 columns]

In [2]:
raw_msgs_df[raw_msgs_df['user'] == "IDIOT😎"]

       user                                        raw_message
314  IDIOT😎      25/07/19, 8:14 pm - IDIOT😎: <Media omitted>\n
315  IDIOT😎  25/07/19, 8:14 pm - IDIOT😎: TCS Code Vita  All...
316  IDIOT😎               25/07/19, 8:29 pm - IDIOT😎: 38 sir\n
317  IDIOT😎               25/07/19, 8:30 pm - IDIOT😎: 92 sir\n
318  IDIOT😎  13/08/19, 6:01 pm - IDIOT😎: Sri Satya Lokesh\n...
319  IDIOT😎  14/08/19, 6:43 pm - IDIOT😎: https://www.infosy...
320  IDIOT😎  07/09/19, 7:53 am - IDIOT😎: https://www.hacker...
321  IDIOT😎  15/09/19, 6:25 pm - IDIOT😎: Participate in thi...
322  IDIOT😎      17/09/19, 5:34 pm - IDIOT😎: <Media omitted>\n
323  IDIOT😎  19/09/19, 11:07 am - IDIOT😎: Replace Plastic I...
324  IDIOT😎     19/09/19, 11:07 am - IDIOT😎: <Media omitted>\n
325  IDIOT😎  17/11/19, 10:40 am - IDIOT😎: Guys anybody havi...
326  IDIOT😎  22/11/19, 8:02 pm - IDIOT😎: Found an article y...
327  IDIOT😎  24/11/19, 8:22 pm - IDIOT😎: Amazon Opening for...
328  IDIOT😎  14/01/20, 10:53 am - IDIOT😎: *Synopsys Inc Mum...
329  IDIOT😎  04/02/20, 9:49 am - IDIOT😎: http://womenofthew...
330  IDIOT😎  28/03/20, 8:22 pm - IDIOT😎: *| Newton School C...
331  IDIOT😎      28/03/20, 8:22 pm - IDIOT😎: <Media omitted>\n
332  IDIOT😎  23/04/20, 5:20 pm - IDIOT😎: *Amazon intern and...

In [0]:
for i in raw_msgs_df.index:
  temp = raw_msgs_df.at[i,'raw_message']
  temp = temp.split(' - ')
  message = temp[1].split(':')
  message = "".join(message[1:])
  raw_msgs_df.at[i,'raw_message'] = message

In [4]:
raw_msgs_df

                user                                        raw_message
0    +91 73311 74849                                          Yes sir\n
1    +91 73311 74849                                  <Media omitted>\n
2    +91 80965 40660    Sir tomm we should attend InfyTQ or Cocubes ?\n
3    +91 80965 40660                         This message was deleted\n
4    +91 98667 58870                                          Infy TQ\n
..               ...                                                ...
632  +91 98483 13908                         This message was deleted\n
633  +91 98483 13908   Sir, most of us are still in assumption that ...
634  +91 79934 07020   Sir, please extend the last date to Monday an...
635  +91 73828 52692   Sir, please extend the last date to Monday an...
636  +91 90106 66088   Yes sir we have already given  ts 1 and 2  to...

[637 rows x 2 columns]

In [5]:
raw_msgs_df[raw_msgs_df['user'] == "IDIOT😎"]

       user                                        raw_message
314  IDIOT😎                                  <Media omitted>\n
315  IDIOT😎                   TCS Code Vita  All India ranks\n
316  IDIOT😎                                           38 sir\n
317  IDIOT😎                                           92 sir\n
318  IDIOT😎                     Sri Satya Lokesh\n16881A0527\n
319  IDIOT😎   https//www.infosys.com/infosys-foundation/aar...
320  IDIOT😎   https//www.hackerearth.com/challenges/hiring/...
321  IDIOT😎   Participate in this exciting machine learning...
322  IDIOT😎                                  <Media omitted>\n
323  IDIOT😎                           Replace Plastic Ideathon
324  IDIOT😎                                  <Media omitted>\n
325  IDIOT😎   Guys anybody having their Wipro interview sch...
326  IDIOT😎   Found an article you may be interested in htt...
327  IDIOT😎   Amazon Opening for Freshers/Students Post Sof...
328  IDIOT😎   *Synopsys Inc Mumbai* is Hiring for the below...
329  IDIOT😎                 http//womenoftheworld.mettl.com/\n
330  IDIOT😎   *| Newton School Coding Challenge | Sunday 29...
331  IDIOT😎                                  <Media omitted>\n
332  IDIOT😎   *Amazon intern and full time SDE hiring*\n\n*...

In [6]:
raw_msgs_df[raw_msgs_df['user'] == "IDIOT😎"]['raw_message'].value_counts()

 <Media omitted>\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             4
 Sri Satya Lokesh\n16881A0527\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                1
 Replace Plastic Ideathon                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
 https//www.infosys.com/infosys-foundation/aarohan-social-innovation-awards/\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
 TCS Code Vita  All India ranks\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1
 38 sir\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
 Guys anybody having their Wipro interview scheduled tomorrow at malla Reddy college of engineering\nThey can attend today itself by our submitted our semester exam Hall ticket\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             1
 Amazon Opening for Freshers/Students Post Software Development Intern \nDuration 6 months\n Qualification Graduation in CS/IT \nPlace Bangalore, Delhi \n\nFor more details, please find the below link\n https//lnkd.in/e5idk6w\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
 Found an article you may be interested in https//www.talview.com/instahiring2020\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
 92 sir\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
 https//www.hackerearth.com/challenges/hiring/valuelabs-frontend-dev-hiring/\n\nExp 0 to 2 years\nCTC 12 LPA\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
 *Amazon intern and full time SDE hiring*\n\n*Eligible stream*  EEE/ECE/EIE/CSE/IT & MCA\n\n*Year of passing*  2021(3rd year) & 2022(2nd year)\n\n*Eligibility criteria*  Female Students with 65% or 6.5 CGPA from tenth onwards with no standing arrears.\n\n*Registration Link* http//www.amazewit.in/amazewow\n\nShare with your juniors\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 1
 Participate in this exciting machine learning challenge and get a chance to land a job at ValueLabs.\n\nexperience                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
 *Synopsys Inc Mumbai* is Hiring for the below two Intern positions\n\nPosition1 \nThe successful candidate will possess following qualifications\n• BE/B. Tech in Computer Science, Software Engineering.\n• Strong concepts of Software Testing Life Cycle.\n• Familiarity with HP UFT and VB Script.\n• Experience in software test automation is a major plus.\n• Demonstrates good analysis and problem-solving skills\n\nPosition2 \nThe successful candidate will possess following qualifications\n• BE/B. Tech in Computer Science, Software Engineering.\n• Strong concepts of Software Testing Life Cycle.\n• Familiarity with TCL and perl scripting.\n• Familiarity with Linux operating system.\n• Experience in software test automation is a major plus.\n• Demonstrates good analysis and problem-solving skills.\n\nInterested candidates    1
 http//womenoftheworld.mettl.com/\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            1
 *| Newton School Coding Challenge | Sunday 29th March 2020 |*\n\n*Newton School* is organizing India's premier *Online Coding Contest* for all the final year Engineering college students across all the colleges in the country. *Compete with India's top university* and have an experience of coding challenges like never before.\n \n*Prize Money Rs.20,000/- and certificate.*\nGood performers get a chance to *interview at Top Product Companies*\n \n*Date of Contest 29th March 2020 (Sunday) at 900 PM to 1130 PM.*\n\n*Apply Here http//bit.ly/39WHGAJ*\n_No Registration Fee!!_\n \n*Essential Steps*\n1) Do the registration by signing up ( If already registered, log-in directly).\n2) Click "Select" in the Newton Coding Challenge box.\n3) Fill up the short form and submit.\n                                                        1
Name: raw_message, dtype: int64

In [0]:
for name in messages.keys():
    df = df.append(pd.DataFrame({'raw_text': messages[name], 'user': name}))

Which is efficient this or chainer?